# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.migration.version", 6);
user_pref("browser.places.smartBookmarksVersion", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage", "about:startpage");
user_pref("browser.startup.homepage_override.mstone", "13.0.1");
user_pref("distribution.linuxdeepin.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.cehomepage.latestVersion", "0.8.6");
user_pref("extensions.cehomepage@mozillaonline.com.install-event-fired", true);
user_pref("extensions.databaseSchema", 12);
user_pref("extensions.dta.saveasmode", 0);
user_pref("extensions.dta.version", "2.0.13");
user_pref("extensions.enabledAddons", "cehomepage@mozillaonline.com:0.8.8,langpack-zh-CN@firefox.mozilla.org:13.0.1,{DDC359D1-844A-42a7-9AA1-88A850A938A8}:2.0.13,{dc572301-7619-498c-a57d-39143191b318}:0.4.0.2,ubufox@ubuntu.com:2.0.3,{972ce4c6-7e08-4474-a285-3208198ce6fd}:13.0.1");
user_pref("extensions.firegestures@xuldev.org.install-event-fired", true);
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1340246988000}}},{\"name\":\"app-global\",\"addons\":{\"cehomepage@mozillaonline.com\":{\"descriptor\":\"/usr/lib/firefox/extensions/cehomepage@mozillaonline.com\",\"mtime\":1340246985000},\"langpack-zh-CN@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-zh-CN@firefox.mozilla.org.xpi\",\"mtime\":1339766962000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1340246985000},\"{DDC359D1-844A-42a7-9AA1-88A850A938A8}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{DDC359D1-844A-42a7-9AA1-88A850A938A8}\",\"mtime\":1340246992000},\"{dc572301-7619-498c-a57d-39143191b318}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{dc572301-7619-498c-a57d-39143191b318}\",\"mtime\":1340250780000}}}]");
user_pref("extensions.lastAppVersion", "13.0.1");
user_pref("extensions.lastPlatformVersion", "13.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.tabmix.dblClickTab", 2);
user_pref("extensions.tabmix.selected_sub_tab1", 0);
user_pref("extensions.tabmix.selected_sub_tab2", 0);
user_pref("extensions.tabmix.selected_sub_tab3", 1);
user_pref("extensions.tabmix.selected_sub_tab4", 0);
user_pref("extensions.tabmix.selected_sub_tab5", 0);
user_pref("extensions.tabmix.selected_sub_tab6", 3);
user_pref("extensions.tabmix.selected_tab", 1);
user_pref("extensions.tabmix.sessions.crashRecovery", false);
user_pref("extensions.tabmix.sessions.crashed", true);
user_pref("extensions.tabmix.sessions.manager", false);
user_pref("extensions.tabmix.version", "0.4.0.2");
user_pref("extensions.ubufox@ubuntu.com.install-event-fired", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.{DDC359D1-844A-42a7-9AA1-88A850A938A8}.install-event-fired", true);
user_pref("extensions.{dc572301-7619-498c-a57d-39143191b318}.install-event-fired", true);
user_pref("intl.charsetmenu.browser.cache", "GB2312, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 51145);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1340250893);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1342842902);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
